backend:
  name: git-gateway
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

publish_mode: editorial_workflow

collections:
  - name: "site"
    label: "Site Content"
    files:
      - file: "content/site.json"
        label: "Main Content"
        name: "main"
        fields:
          - { label: "Business Name", name: "businessName", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Tagline", name: "tagline", widget: "string" }
          - { label: "About", name: "about", widget: "text" }
          - label: "Services"
            name: "services"
            widget: "list"
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
