backend:
  name: github
  repo: BLS2018/benslawnservices
  branch: main

media_folder: "assets/img"
public_folder: "/assets/img"

collections:
  - label: "Main Content"
    name: "site"
    files:
      - label: "Site Content"
        name: "site"
        file: "content/site.json"
        fields:
          - {label: "Headline", name: "headline", widget: "string", required: false}
          - {label: "About", name: "about", widget: "text", required: false}
          - {label: "Phone", name: "phone", widget: "string", required: false}
          - {label: "Email", name: "email", widget: "string", required: false}
          - {label: "Services", name: "services", widget: "list", required: false, fields: [{label:"Title", name:"title", widget:"string"}, {label:"Description", name:"description", widget:"text", required:false}]}
