backend:
  name: github
  repo: BLS2018/benslawnservices
  branch: main

media_folder: "static/img" # Folder where uploaded files go in your repo
public_folder: "/img"      # Public URL path for those files

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
